services:
  backend:
    build: ./backend
    container_name: qr-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: qr-frontend
    ports:
      - "3000:80"
